version: '3'

services:
  db:
    image: "postgres"
    container_name: craft-app-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data/pgdata

volumes:
  data-volume: