version: '3'

services:
  db:
    image: "postgres"
    container_name: craft-app-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data/pgdata
    networks:
      - backend

  craft-app:
    image: "ernez/craftapp"
    build: .
    container_name: craftapp
    ports:
      - "8080:8081"
    environment:
      SPRING_DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data/pgdata
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend


volumes:
  data-volume:
# Networks to be created to facilitate communication between containers
networks:
  backend:
