version: '3'

services:
  db:
    image: "postgres"
    container_name: craft-app-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data/pgdata

#  craft-app:
#    image: "ernez/craft-app"
#    build: .
#    container_name: craft-app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 123
#    depends_on:
#      - db

volumes:
  data-volume:
