server.port: 8081

#security.basic.enabled: false
spring.security.user:
  name: admin
  password: secret



# Generates the database *only* if it's not there yet
spring.jpa.hibernate.ddl-auto: update
## Creates the database in a file
spring.datasource:
  url: ${SPRING_DATABASE_URL}
  driverClassName: org.postgresql.Driver
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}


#****************************
## For educational purposes we will show the SQL in console
spring.jpa.properties.hibernate.show_sql: true

#/h2-console

logging:
  level:
    org:
      springframework:
        web: INFO
        context: INFO
      hibernate: ERROR
    web: INFO

#show sql statement
logging.level.org.hibernate.SQL: DEBUG
#show sql values
logging.level.org.hibernate.type.descriptor.sql: DEBUG

spring.jpa.show-sql: true
